name: Update Repository List

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  update-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch repository data
        id: repo-data
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = context.repo.owner;
            const query = `
              query($username: String!) {
                user(login: $username) {
                  repositories(first: 100, privacy: PUBLIC, orderBy: {field: UPDATED_AT, direction: DESC}) {
                    nodes {
                      name
                      description
                      url
                      updatedAt
                      stargazerCount
                      forkCount
                      isArchived
                      isTemplate
                      primaryLanguage {
                        name
                      }
                      isFork
                    }
                  }
                }
              }
            `;

            const variables = {
              username: username
            };

            const result = await github.graphql(query, variables);
            const repos = result.user.repositories.nodes.map(repo => ({
              name: repo.name,
              description: repo.description,
              url: repo.url,
              updatedAt: repo.updatedAt,
              stargazerCount: repo.stargazerCount,
              forkCount: repo.forkCount,
              isArchived: repo.isArchived,
              isTemplate: repo.isTemplate,
              language: repo.primaryLanguage ? repo.primaryLanguage.name : null,
              fork: repo.isFork
            }));

            const fs = require('fs');
            fs.writeFileSync('assets/repos.json', JSON.stringify(repos, null, 2));
            console.log(`Successfully fetched ${repos.length} repositories`);

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add assets/repos.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update repository list"
          git push
